SELECT Nom FROM Heros ORDER BY Nom ASC;

SELECT Nom,PV FROM Heros WHERE PV=40;

SELECT Nom,PV FROM Heros WHERE PV=40 

SELECT COUNT(*) FROM Heros WHERE PV=40;

SELECT * FROM Heros ORDER BY PV ASC;

SELECT Nom,PV FROM Heros ORDER BY PV DESC LIMIT 1;

SELECT SUM(PV) FROM Heros;

